# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Publish release assets

on:
  release:
    types: ['published']

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20.x

    - name: Mod tidy
      run: go mod tidy

    - name: Linux build
      run: |
        go build -o cmd/sdwanctl .
        cd ./cmd
        tar -czf sdwanctl-linux-${{ github.event.release.tag_name }}.tar.gz ./sdwanctl
        rm ./sdwanctl

    - name: Windows build
      run: |
        GOOS=windows GOARCH=amd64 go build -o cmd/sdwanctl.exe .
        cd ./cmd
        zip sdwanctl-windows-${{ github.event.release.tag_name }}.zip ./sdwanctl.exe
        rm ./sdwanctl.exe

    - name: Darwin build
      run: |
        GOOS=darwin GOARCH=amd64 go build -o cmd/sdwanctl .
        cd ./cmd
        tar -czf sdwanctl-darwin-${{ github.event.release.tag_name }}.tar.gz ./sdwanctl
        rm ./sdwanctl

    - name: Upload release assets
      uses: softprops/action-gh-release@v1
      with:
        files: |
          cmd/sdwanctl-darwin-${{ github.event.release.tag_name }}.tar.gz
          cmd/sdwanctl-linux-${{ github.event.release.tag_name }}.tar.gz
          cmd/sdwanctl-windows-${{ github.event.release.tag_name }}.zip

    - name: Upload linux artifact
      uses: actions/upload-artifact@v3
      with:
        name: sdwanctl-linux-${{ github.event.release.tag_name }}.tar.gz
        path: cmd/sdwanctl-linux-${{ github.event.release.tag_name }}.tar.gz

    - name: Upload windows artifact
      uses: actions/upload-artifact@v3
      with:
        name: sdwanctl-windows-${{ github.event.release.tag_name }}.zip
        path: cmd/sdwanctl-windows-${{ github.event.release.tag_name }}.tar.gz





